#-------------------------------
# General Site Settings

title: F. W
description: A pseudo physicist. # this means to ignore newlines until "baseurl:"
owner:
  name: Fang Wang
  url: "http://www.wang-axiom.com" # your URL
first_published: 2020 # if migrating another site, the year of your first publish
                      # Must be a 4-digit integer year (math is used on it)
url: "http://www.wang-axiom.com" # the base hostname & protocol for this site
baseurl: "" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.

#-------------------------------
# About Section
author-name:   Fang Wang
author-avatar: 01.jpg


#-------------------------------
# Contact links
facebook:  https://www.facebook.com/profile.php?id=100005392728939 # Add your Facebook handle
instagram: https://www.instagram.com/fang_wang1992/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:categories/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/page/:num"

include: ['_pages']

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
